services:
    db:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        container_name: postgres
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - '5432:5432'
  

    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        container_name: nest-docker-postgres
        environment:
            - PORT=${APP_PORT}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_DATABASE=${DB_DATABASE}
            - DB_HOST=db
            - DB_PORT=${DB_PORT}
            - DB_LOGGING=${DB_LOGGING}
            - JWT_TOKEN=${JWT_TOKEN}
        ports:
            - '${APP_PORT}:${APP_PORT}'
        entrypoint: wait-for db:5432 -t 40 -- npm run start:prod
        depends_on:
            - db